name: Build
on:
  - push

jobs:
  build:
    name: "Build"
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'
      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install
      - name: Build WASM file
        run: yarn asbuild

  test:
    name: "Tests"
    timeout-minutes: 5
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'
      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install
      - name: Build WASM file
        run: yarn asbuild:test
      - name: Run encoding tests
        run: node tests/encoding.test.js
      - name: Run decoding tests
        run: node tests/decoding.test.js
